name: typed_serializer
description: >
  TypedSerializer is a mixin that adds methods to convert objects
  from type to type using typed definitions and detectors for auto
  detect object type.

repository: https://github.com/Davenchy/typed_serializer
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
